---
title: "Amp Eff Punnet Square Exploration"
author: "Zack Gold"
date: "12/2/2021"
output: html_document
---

```{r}
library(tidyverse)
library(here)
library(ggpmisc)
```

```{r, function for transforming eDNA Index,results='hide'}
load(here("data","Stan_Fit_combined_20210929_1338.RData"))
stanMod <- Output$stanMod

pars_alpha <- rstan::extract(stanMod, par = "a_mifish")

Output$stan_pars
species_mapping <-  Output$species_mapping %>%  mutate(., ID_main = str_replace(ID_main, "AANOTHER","sp."))
dim(species_mapping)

pars_alpha$a_mifish %>%
   as_tibble() %>%
   pivot_longer(., cols = `V1`:`V54`, names_to="Species", values_to = "est") %>% 
  group_by(Species) %>% 
  dplyr::summarise(amp_eff= mean(est)) %>% 
  mutate(., sp_index_mifish = str_replace(Species, "V","")) %>% 
  mutate(sp_index_mifish=as.integer(sp_index_mifish)) %>% 
  left_join(species_mapping) %>% 
  mutate(., Unique_ID=ID_main)-> amp_eff_means 
  
```

```{r}
MiFish_data <- readRDS(file = here("data", "mifish_tech_nReads.RDS"))

MiFish_data %>% 
  filter(., ID_mifish!= "MISSING") -> MiFish_data 



MiFish_data %>% 
  as_tibble() %>% 
  ungroup() %>% 
  filter(., !is.na(mifish_reads)) %>% 
  group_by(ID_mifish,station_id,ext_rep) %>% 
  dplyr::summarise(meanReads = mean(mifish_reads),
            sdReads = sd(mifish_reads)) %>%
  filter(meanReads > 0) %>% 
  ungroup() %>% 
  mutate(cvReads = sdReads/meanReads) %>% 
  drop_na() -> cv_calcofi

cv_calcofi %>% 
  ggplot(aes(x = meanReads, y = cvReads)) +
  geom_point()
```

```{r}

MiFish_data %>% 
  as_tibble() %>% 
  ungroup() %>% 
  filter(., !is.na(mifish_reads)) %>% 
  group_by(Sample) %>% 
  dplyr::summarise(., tot_reads=sum(mifish_reads)) -> tot_reads_calcofi

MiFish_data %>% 
    filter(., !is.na(mifish_reads)) %>% 
  left_join(tot_reads_calcofi) %>% 
  mutate(., proportion=mifish_reads/tot_reads) %>% 
  ungroup() %>% 
  group_by(ID_mifish,station_id,ext_rep) %>% 
  dplyr::summarise(mean_prop = mean(proportion),
                   max_prop=max(proportion),
                   min_prop=min(proportion)) ->  avg_data_calcofi

MiFish_data %>% 
    filter(., !is.na(mifish_reads)) %>%  
 left_join(avg_data_calcofi) %>% 
  left_join(tot_reads_calcofi) %>% 
  mutate(., proportion=mifish_reads/tot_reads) %>% 
  mutate(zero_inf = case_when(min_prop > 0 & max_prop > 0 ~"Three reps above zero",
                              min_prop == 0 & max_prop > 0 ~"One rep is zero",
                              min_prop == 0 & max_prop == 0 ~"All zero")) %>% 
  filter(., zero_inf != "All zero") -> calcofi_counts

calcofi_counts %>% 
  group_by(ID_mifish) %>% 
  count(zero_inf) %>% 
  filter(., n >10) %>% 
  filter(., !str_detect(ID_mifish,"Sebastes"))-> species_to_keep

calcofi_counts %>% 
  as.tibble() %>% 
  filter(., ID_mifish %in% species_to_keep$ID_mifish) %>% 
  mutate( tech_rep=as.character(tech_rep)) %>% 
  left_join(amp_eff_means) -> for_plotting

for_plotting %>% 
  ggplot(aes(x=tot_reads, y=proportion, color=zero_inf, shape=tech_rep)) +geom_point() +facet_wrap(ID_mifish~.,scales = "free") -> plot_prop

ggsave(plot=plot_prop,here("species_prop_plot.png"), device = "png", width = 30, height = 30, units = "in")

amp_eff_means %>% 
  ggplot(aes(x=amp_eff)) + geom_histogram()

for_plotting %>% 
  filter(., amp_eff > 0.7) %>% 
  ggplot(aes(x=tot_reads, y=proportion, color=zero_inf, shape=tech_rep)) +geom_point() +facet_wrap(ID_mifish~.,scales = "free") -> plot_prop_high_amp

ggsave(plot=plot_prop_high_amp,here("species_prop_plot_high_amp.png"), device = "png", width = 12, height = 8, units = "in")

for_plotting %>% 
  filter(., amp_eff < 0.7) %>% 
  ggplot(aes(x=tot_reads, y=proportion, color=zero_inf, shape=tech_rep)) +geom_point() +facet_wrap(ID_mifish~.,scales = "free") -> plot_prop_low_amp

ggsave(plot=plot_prop_low_amp,here("species_prop_plot_low_amp.png"), device = "png", width = 12, height = 8, units = "in")

```

```{r}
for_plotting %>% 
  ggplot(aes(x=tot_reads, y=mifish_reads, color=zero_inf, shape=tech_rep)) +geom_point() +facet_wrap(ID_mifish~.,scales = "free") -> plot_reads 

ggsave(plot=plot_reads,here("plot_reads_plot.png"), device = "png", width = 30, height = 30, units = "in")

amp_eff_means %>% 
  ggplot(aes(x=amp_eff)) + geom_histogram()

for_plotting %>% 
  filter(., amp_eff > 0.7) %>% 
  ggplot(aes(x=tot_reads, y=mifish_reads, color=zero_inf, shape=tech_rep)) +geom_point() +facet_wrap(ID_mifish~.,scales = "free") -> plot_reads_high_amp

ggsave(plot=plot_reads_high_amp,here("plot_reads_high_amp.png"), device = "png", width = 12, height = 8, units = "in")

for_plotting %>% 
  filter(., amp_eff < 0.7) %>% 
  ggplot(aes(x=tot_reads, y=mifish_reads, color=zero_inf, shape=tech_rep)) +geom_point() +facet_wrap(ID_mifish~.,scales = "free") -> plot_reads_low_amp

ggsave(plot=plot_reads_low_amp,here("plot_reads_low_amp.png"), device = "png", width = 12, height = 8, units = "in")

```

```{r}
MiFish_data %>% 
    filter(., !is.na(mifish_reads)) %>% 
  dplyr::select(-Sample) %>% 
  pivot_wider(values_from="mifish_reads", names_from="tech_rep") %>%
  filter(., !str_detect(Unique_ID,"Sebastes")) -> mifish_wide

MiFish_data %>% 
    filter(., !is.na(mifish_reads)) %>% 
  ungroup() %>% 
  group_by(ID_mifish,station_id,ext_rep) %>% 
  dplyr::summarise(mean_reads = mean(mifish_reads),
                   max_reads=max(mifish_reads),
                   min_reads=min(mifish_reads)) ->  avg_data_calcofi_reads

avg_data_calcofi_reads %>% 
  filter(., mean_reads >0) %>% 
  filter(., min_reads==0)  -> concerning_reps

concerning_reps %>% 
  left_join(mifish_wide) %>% 
  left_join(amp_eff_means) %>% View()
```

```{r}
MiFish_data %>% 
  as_tibble() %>% 
  ungroup() %>% 
  filter(., !is.na(mifish_reads)) %>% 
  group_by(station_id,ext_rep) %>% 
  dplyr::summarise(., tot_reads=sum(mifish_reads)) -> tot_reads_calcofi_2

cv_calcofi %>% 
  left_join(tot_reads_calcofi_2) %>% 
    filter(., ID_mifish %in% species_to_keep$ID_mifish) %>% 
  ggplot(aes(x = tot_reads, y = cvReads)) +
  geom_point()+facet_wrap(ID_mifish~.) -> cv_species


ggsave(plot=cv_species,here("cv_species.png"), device = "png", width = 12, height = 8, units = "in")

```

```{r}
cv_calcofi %>% 
  ungroup() %>% 
  group_by(ID_mifish) %>% 
  dplyr::summarise(mean(cvReads), sd(cvReads), max(cvReads), min(cvReads)) %>% 
  left_join(amp_eff_means) %>% 
  ggplot(aes(x=amp_eff,y=`mean(cvReads)`)) +geom_point() +geom_smooth(method="lm") + 
  stat_poly_eq(formula = y~x, 
                aes(label = paste(..rr.label..,..p.value.label.., sep = "~~~")), 
                parse = TRUE,
               label.x = 1.5,
  label.y = 0.1, p.digits =2, rr.digits = 2,size = 7) -> meancv_vs_amp_eff

ggsave(plot=meancv_vs_amp_eff,here("meancv_vs_amp_eff.png"), device = "png", width = 12, height = 8, units = "in")


```

```{r}
cv_calcofi %>% 
  ungroup() %>% 
  left_join(amp_eff_means) %>% 
  filter(!is.na(amp_eff)) %>% 
   mutate(Amplification_eff = case_when(amp_eff > 0.75 ~"> 0.75",
                              amp_eff > 0.6  ~"> 0.6",
                              TRUE ~"< 0.6")) %>% 
  ggplot(aes(x=Amplification_eff,y=cvReads)) +geom_boxplot() -> cv_vs_amp_eff

ggsave(plot=cv_vs_amp_eff,here("cv_vs_amp_eff.png"), device = "png", width = 12, height = 8, units = "in")

```


```{r}
cv_calcofi %>% 
  mutate(., Year = str_sub(station_id,1,4)) %>% 
  filter(., Year =="2015") %>% 
  left_join(amp_eff_means) %>% 
   ggplot(aes(x=amp_eff,y=cvReads)) +geom_point() +geom_smooth(method="lm") + 
  stat_poly_eq(formula = y~x, 
                aes(label = paste(..rr.label..,..p.value.label.., sep = "~~~")), 
                parse = TRUE,
               label.x = 1.5,
  label.y = 0.1, p.digits =2, rr.digits = 2,size = 7) +facet_wrap(station_id~.) -> cv_vs_amp_eff_2015

ggsave(plot=cv_vs_amp_eff_2015,here("cv_vs_amp_eff_2015.png"), device = "png", width = 12, height = 8, units = "in")


cv_calcofi %>% 
  mutate(., Year = str_sub(station_id,1,4)) %>% 
  filter(., Year =="2015") %>% 
  left_join(amp_eff_means) %>% 
   ggplot(aes(x=amp_eff,y=log(meanReads))) +geom_point() +geom_smooth(method="lm") + 
  stat_poly_eq(formula = y~x, 
                aes(label = paste(..rr.label..,..p.value.label.., sep = "~~~")), 
                parse = TRUE,
               label.x = 1.5,
  label.y = 0.1, p.digits =2, rr.digits = 2,size = 7) +facet_wrap(station_id~.) 

```

```{r}
cv_calcofi %>% 
  filter(., station_id =="2015_80_60") %>% 
  left_join(amp_eff_means) %>% 
  ggplot(aes(x=ID_mifish,y=cvReads)) +geom_point() +
  theme(axis.text.x = element_text(angle =30, hjust=1)) ->cv_2015_80_60

cv_calcofi %>% 
  filter(., station_id =="2015_80_60") %>% 
  left_join(amp_eff_means) %>% 
  ggplot(aes(x=ID_mifish,y=meanReads)) +geom_point() +
  theme(axis.text.x = element_text(angle =30, hjust=1)) -> mean_reads_2015_80_60


cv_calcofi %>% 
  filter(., station_id =="2015_80_60") %>% 
  left_join(amp_eff_means) %>% 
  ggplot(aes(x=meanReads,y=cvReads)) +geom_point() +
  theme(axis.text.x = element_text(angle =30, hjust=1)) -> cv_vs_mean_reads_2015_80_60


for_plotting %>% 
   filter(., station_id =="2015_80_60") %>% 
  ggplot(aes(x=ID_mifish, y=mifish_reads, color=zero_inf, shape=tech_rep)) +geom_point() +
  theme(axis.text.x = element_text(angle =30, hjust=1)) -> zero_inf_2015_80_60


library(patchwork)

(cv_2015_80_60 + mean_reads_2015_80_60)/
  (cv_vs_mean_reads_2015_80_60 + zero_inf_2015_80_60 + plot_layout(byrow = F, widths = c(3,3), ncol = 2)) + 
    plot_annotation(tag_levels = "A",title = "2015_80_60")

ggsave(filename = "2015_80_60.png",
       width=18,
       height = 12,
       dpi = 400,
       units = c("in"))


cv_calcofi %>% 
    filter(., station_id =="2015_80_60") %>% 
  left_join(amp_eff_means) %>% 
   ggplot(aes(x=amp_eff,y=cvReads, color=ID_mifish)) +geom_point() +theme(legend.position = "none") -> cv_amp_ef_2015_80_60

cv_calcofi %>% 
    filter(., station_id =="2015_80_60") %>% 
  left_join(amp_eff_means) %>% 
  filter(!is.na(amp_eff)) %>% 
   ggplot(aes(x=amp_eff,y=log(meanReads), color=ID_mifish)) +geom_point()  -> mean_reads_amp_ef_2015_80_60


cv_amp_ef_2015_80_60+mean_reads_amp_ef_2015_80_60 + 
    plot_annotation(tag_levels = "A",title = "2015_80_60")

ggsave(filename = "2015_80_60_amp_eff.png",
       width=18,
       height = 12,
       dpi = 200,
       units = c("in"))


for_plotting %>% 
   filter(., station_id =="2015_80_60") %>% 
  ggplot(aes(x=ID_mifish, y=mifish_reads, color=zero_inf, shape=tech_rep)) +geom_point() +
  theme(axis.text.x = element_text(angle =30, hjust=1)) + facet_wrap(~ID_mifish, scales="free")-> zero_inf_2015_80_60

zero_inf_2015_80_60
ggsave(filename = "zero_inf_2015_80_60.png",
       width=18,
       height = 12,
       dpi = 200,
       units = c("in"))


```

```{r}
cv_calcofi %>% 
  filter(., station_id =="2015_93.3_30") %>% 
  left_join(amp_eff_means) %>% 
  ggplot(aes(x=ID_mifish,y=cvReads)) +geom_point() +
  theme(axis.text.x = element_text(angle =30, hjust=1)) ->cv_2015_93.3_30

cv_calcofi %>% 
  filter(., station_id =="2015_93.3_30") %>% 
  left_join(amp_eff_means) %>% 
  ggplot(aes(x=ID_mifish,y=meanReads)) +geom_point() +
  theme(axis.text.x = element_text(angle =30, hjust=1)) -> mean_reads_2015_93.3_30


cv_calcofi %>% 
  filter(., station_id =="2015_93.3_30") %>% 
  left_join(amp_eff_means) %>% 
  ggplot(aes(x=meanReads,y=cvReads)) +geom_point() +
  theme(axis.text.x = element_text(angle =30, hjust=1)) -> cv_vs_mean_reads_2015_93.3_30


for_plotting %>% 
   filter(., station_id =="2015_93.3_30") %>% 
  ggplot(aes(x=ID_mifish, y=mifish_reads, color=zero_inf, shape=tech_rep)) +geom_point() +
  theme(axis.text.x = element_text(angle =30, hjust=1)) -> zero_inf_2015_93.3_30


library(patchwork)

(cv_2015_93.3_30 + mean_reads_2015_93.3_30)/
  (cv_vs_mean_reads_2015_93.3_30 + zero_inf_2015_93.3_30 + plot_layout(byrow = F, widths = c(3,3), ncol = 2)) + 
    plot_annotation(tag_levels = "A",title = "2015_93.3_30")

ggsave(filename = "2015_93.3_30.png",
       width=18,
       height = 12,
       dpi = 400,
       units = c("in"))


cv_calcofi %>% 
    filter(., station_id =="2015_93.3_30") %>% 
  left_join(amp_eff_means) %>% 
   ggplot(aes(x=amp_eff,y=cvReads, color=ID_mifish)) +geom_point() +theme(legend.position = "none") -> cv_amp_ef_2015_93.3_30

cv_calcofi %>% 
    filter(., station_id =="2015_93.3_30") %>% 
  left_join(amp_eff_means) %>% 
  filter(!is.na(amp_eff)) %>% 
   ggplot(aes(x=amp_eff,y=log(meanReads), color=ID_mifish)) +geom_point()  -> mean_reads_amp_ef_2015_93.3_30


cv_amp_ef_2015_93.3_30+mean_reads_amp_ef_2015_93.3_30 + 
    plot_annotation(tag_levels = "A",title = "2015_93.3_30")

ggsave(filename = "2015_93.3_30_amp_eff.png",
       width=18,
       height = 12,
       dpi = 200,
       units = c("in"))


for_plotting %>% 
   filter(., station_id =="2015_93.3_30") %>% 
  ggplot(aes(x=ID_mifish, y=mifish_reads, color=zero_inf, shape=tech_rep)) +geom_point() +
  theme(axis.text.x = element_text(angle =30, hjust=1)) + facet_wrap(~ID_mifish, scales="free")-> zero_inf_2015_93.3_30

zero_inf_2015_93.3_30
ggsave(filename = "zero_inf_2015_93.3_30.png",
       width=18,
       height = 12,
       dpi = 200,
       units = c("in"))

for_plotting %>% 
   filter(., station_id =="2015_93.3_30") %>% select(tot_reads) %>%  unique()

for_plotting %>% 
   filter(., station_id =="2015_80_60") %>% select(tot_reads) %>%  unique()
```

```{r}
cv_calcofi %>% 
  filter(., station_id =="2015_93.3_60") %>% 
  left_join(amp_eff_means) %>% 
  ggplot(aes(x=ID_mifish,y=cvReads)) +geom_point() +
  theme(axis.text.x = element_text(angle =30, hjust=1)) ->cv_2015_93.3_60

cv_calcofi %>% 
  filter(., station_id =="2015_93.3_60") %>% 
  left_join(amp_eff_means) %>% 
  ggplot(aes(x=ID_mifish,y=meanReads)) +geom_point() +
  theme(axis.text.x = element_text(angle =30, hjust=1)) -> mean_reads_2015_93.3_60


cv_calcofi %>% 
  filter(., station_id =="2015_93.3_60") %>% 
  left_join(amp_eff_means) %>% 
  ggplot(aes(x=meanReads,y=cvReads)) +geom_point() +
  theme(axis.text.x = element_text(angle =30, hjust=1)) -> cv_vs_mean_reads_2015_93.3_60


for_plotting %>% 
   filter(., station_id =="2015_93.3_60") %>% 
  ggplot(aes(x=ID_mifish, y=mifish_reads, color=zero_inf, shape=tech_rep)) +geom_point() +
  theme(axis.text.x = element_text(angle =30, hjust=1)) -> zero_inf_2015_93.3_60


library(patchwork)

(cv_2015_93.3_60 + mean_reads_2015_93.3_60)/
  (cv_vs_mean_reads_2015_93.3_60 + zero_inf_2015_93.3_60 + plot_layout(byrow = F, widths = c(3,3), ncol = 2)) + 
    plot_annotation(tag_levels = "A",title = "2015_93.3_60")

ggsave(filename = "2015_93.3_60.png",
       width=18,
       height = 12,
       dpi = 400,
       units = c("in"))


cv_calcofi %>% 
    filter(., station_id =="2015_93.3_60") %>% 
  left_join(amp_eff_means) %>% 
   ggplot(aes(x=amp_eff,y=cvReads, color=ID_mifish)) +geom_point() +theme(legend.position = "none") -> cv_amp_ef_2015_93.3_60

cv_calcofi %>% 
    filter(., station_id =="2015_93.3_60") %>% 
  left_join(amp_eff_means) %>% 
  filter(!is.na(amp_eff)) %>% 
   ggplot(aes(x=amp_eff,y=log(meanReads), color=ID_mifish)) +geom_point()  -> mean_reads_amp_ef_2015_93.3_60


cv_amp_ef_2015_93.3_60+mean_reads_amp_ef_2015_93.3_60 + 
    plot_annotation(tag_levels = "A",title = "2015_93.3_60")

ggsave(filename = "2015_93.3_60_amp_eff.png",
       width=18,
       height = 12,
       dpi = 200,
       units = c("in"))


for_plotting %>% 
   filter(., station_id =="2015_93.3_60") %>% 
  ggplot(aes(x=ID_mifish, y=mifish_reads, color=zero_inf, shape=tech_rep)) +geom_point() +
  theme(axis.text.x = element_text(angle =30, hjust=1)) + facet_wrap(~ID_mifish, scales="free")-> zero_inf_2015_93.3_60

zero_inf_2015_93.3_60
ggsave(filename = "zero_inf_2015_93.3_60.png",
       width=18,
       height = 12,
       dpi = 200,
       units = c("in"))

for_plotting %>% 
   filter(., station_id =="2015_93.3_60") %>% select(tot_reads) %>%  unique()

for_plotting %>% 
   filter(., station_id =="2015_80_60") %>% select(tot_reads) %>%  unique()
```

```{r}

MiFish_data %>% 
  group_by(ID_mifish,station_id,ext_rep) %>% 
  dplyr::summarise(sum_jar = sum(mifish_reads, na.rm = TRUE)) %>% 
  filter(., sum_jar >0) %>% 
  group_by(ID_mifish) %>% 
  count() %>% 
  arrange(desc(n)) %>% 
  left_join(amp_eff_means) %>% 
  ggplot(.,aes(x=amp_eff, y=n)) +geom_point() + geom_smooth(method="lm") + 
  stat_poly_eq(formula = y~x, 
                aes(label = paste(..rr.label..,..p.value.label.., sep = "~~~")), 
                parse = TRUE,
               label.x = 1.5,
  label.y = 0.1, p.digits =2, rr.digits = 2,size = 7) -> count_obs_vs_amp_eff


MiFish_data %>% 
  group_by(ID_mifish) %>% 
  dplyr::summarise(tot_reads = sum(mifish_reads, na.rm = TRUE)) %>% 
  filter(., tot_reads >0) %>% 
  arrange(desc(tot_reads)) %>% 
  filter(., ID_mifish != "Sebastes") %>% 
  left_join(amp_eff_means) %>% 
  ggplot(.,aes(x=amp_eff, y=log(tot_reads))) +geom_point() + geom_smooth(method="lm") + 
  stat_poly_eq(formula = y~x, 
                aes(label = paste(..rr.label..,..p.value.label.., sep = "~~~")), 
                parse = TRUE,
               label.x = 1.5,
  label.y = 0.1, p.digits =2, rr.digits = 2,size = 7) -> tot_reads_obs_vs_amp_eff


count_obs_vs_amp_eff/tot_reads_obs_vs_amp_eff

ggsave(filename = "amp_eff_explained_by_tot_reads.png",
       width=18,
       height = 12,
       dpi = 200,
       units = c("in"))

```




```{r}
larvae_data <- readRDS(file = here("data", "microscopy_tech_nReads.RDS"))

larvae_data %>% 
  filter(., ID_mifish =="Engraulis mordax") %>% 
  ggplot(aes(x=larval_counts)) +geom_histogram()


larvae_data %>% 
  filter(., ID_mifish =="Engraulis mordax") %>% 
   mutate(chovy_level = case_when(larval_counts > 100  ~"High",
                              larval_counts >10  ~"Medium",
                              larval_counts >0  ~"Low",
                              TRUE ~"Not Counted")) ) -> chovy_count


cv_calcofi %>% 
  filter(., ID_mifish=="Engraulis mordax") %>% 
  left_join(chovy_count) %>% 
  ggplot(aes(x=larval_counts,y=cvReads)) +geom_point() +ggtitle("Anchovy")

ggsave(filename = "Anchovy_cv_vs_larval_counts.png",
       width=18,
       height = 12,
       dpi = 200,
       units = c("in"))


for_plotting %>% 
  filter(., ID_mifish =="Engraulis mordax") %>% 
  left_join(chovy_count) %>% 
  ggplot(aes(x=larval_counts, y=mifish_reads, color=zero_inf, shape=tech_rep)) +geom_point() +
  theme(axis.text.x = element_text(angle =30, hjust=1)) + facet_wrap(~ID_mifish, scales="free")

ggsave(filename = "Anchovy_tech_rep_zero.png",
       width=18,
       height = 12,
       dpi = 200,
       units = c("in"))


for_plotting %>% 
  filter(., ID_mifish =="Engraulis mordax") %>% 
  left_join(chovy_count) %>% 
  ggplot(aes(x=larval_counts, y=proportion, color=zero_inf, shape=tech_rep)) +geom_point() +
  theme(axis.text.x = element_text(angle =30, hjust=1)) + facet_wrap(~ID_mifish, scales="free")

ggsave(filename = "Anchovy_tech_rep_zero_prop.png",
       width=18,
       height = 12,
       dpi = 200,
       units = c("in"))


for_plotting %>% 
  filter(., ID_mifish =="Engraulis mordax") %>% 
  left_join(chovy_count) %>% 
  ggplot(aes(x=Year, y=proportion, color=zero_inf, shape=tech_rep)) +geom_point() +
  theme(axis.text.x = element_text(angle =30, hjust=1)) +facet_wrap(chovy_level~.)

ggsave(filename = "Anchovy_tech_rep_zero_prop_station.png",
       width=18,
       height = 12,
       dpi = 200,
       units = c("in"))

for_plotting %>% 
  filter(., ID_mifish =="Engraulis mordax") %>% 
  left_join(chovy_count) %>% 
  ggplot(aes(x=Year, y=proportion, color=zero_inf, shape=tech_rep)) +geom_point() +
  theme(axis.text.x = element_text(angle =30, hjust=1)) +facet_wrap(chovy_level~.)

ggsave(filename = "Anchovy_tech_rep_zero_prop_count_level.png",
       width=18,
       height = 12,
       dpi = 200,
       units = c("in"))



  

```

```{r}
larvae_data %>% 
  filter(., ID_mifish =="Sardinops sagax") %>% 
  ggplot(aes(x=larval_counts)) +geom_histogram()


larvae_data %>% 
  filter(., ID_mifish =="Sardinops sagax") %>% 
   mutate(chovy_level = case_when(larval_counts > 100  ~"High",
                              larval_counts >10  ~"Medium",
                              larval_counts >0  ~"Low",
                              TRUE ~"Not Counted"))  -> sard_count


cv_calcofi %>% 
  filter(., ID_mifish=="Sardinops sagax") %>% 
  left_join(sard_count) %>% 
  ggplot(aes(x=larval_counts,y=cvReads)) +geom_point() +ggtitle("Sardine")

ggsave(filename = "sardine_cv_vs_larval_counts.png",
       width=18,
       height = 12,
       dpi = 200,
       units = c("in"))


for_plotting %>% 
  filter(., ID_mifish =="Sardinops sagax") %>% 
  left_join(sard_count) %>% 
  ggplot(aes(x=larval_counts, y=mifish_reads, color=zero_inf, shape=tech_rep)) +geom_point() +
  theme(axis.text.x = element_text(angle =30, hjust=1)) + facet_wrap(~ID_mifish, scales="free")



for_plotting %>% 
  filter(., ID_mifish =="Sardinops sagax") %>% 
  left_join(sard_count) %>% 
  ggplot(aes(x=larval_counts, y=proportion, color=zero_inf, shape=tech_rep)) +geom_point() +
  theme(axis.text.x = element_text(angle =30, hjust=1)) + facet_wrap(~ID_mifish, scales="free")


for_plotting %>% 
  filter(., ID_mifish =="Sardinops sagax") %>% 
  left_join(sard_count) %>% 
  ggplot(aes(x=Year, y=proportion, color=zero_inf, shape=tech_rep)) +geom_point() +
  theme(axis.text.x = element_text(angle =30, hjust=1)) +facet_wrap(chovy_level~.)



ggsave(filename = "sardine_vs_count_drop_out.png",
       width=18,
       height = 12,
       dpi = 200,
       units = c("in"))
  

```


```{r}

larvae_data %>% 
  group_by(ID_mifish) %>% 
  dplyr::summarise(sum(larval_counts)) %>% 
  arrange(desc(`sum(larval_counts)`)) %>% 
  filter(., ID_mifish != "Sebastes") %>% 
  left_join(amp_eff_means) %>% 
  filter(., `sum(larval_counts)` > 20) %>% 
  ggplot(aes(x=`sum(larval_counts)`, y=amp_eff, color=ID_mifish)) + geom_point()

```

```{r}
larvae_data %>% 
  filter(., ID_mifish =="Merluccius productus") %>% 
  ggplot(aes(x=larval_counts)) +geom_histogram()


larvae_data %>% 
  filter(., ID_mifish =="Merluccius productus") %>% 
   mutate(chovy_level = case_when(larval_counts > 10  ~"High",
                              larval_counts >5  ~"Medium",
                              larval_counts >0  ~"Low",
                              TRUE ~"Not Counted"))  -> hake_count


cv_calcofi %>% 
  filter(., ID_mifish=="Merluccius productus") %>% 
  left_join(hake_count) %>% 
  ggplot(aes(x=larval_counts,y=cvReads)) +geom_point() +ggtitle("Hake")

ggsave(filename = "hake_cv_vs_larval_counts.png",
       width=18,
       height = 12,
       dpi = 200,
       units = c("in"))


for_plotting %>% 
  filter(., ID_mifish =="Merluccius productus") %>% 
  left_join(hake_count) %>% 
  ggplot(aes(x=larval_counts, y=mifish_reads, color=zero_inf, shape=tech_rep)) +geom_point() +
  theme(axis.text.x = element_text(angle =30, hjust=1)) + facet_wrap(~ID_mifish, scales="free")



for_plotting %>% 
  filter(., ID_mifish =="Merluccius productus") %>% 
  left_join(hake_count) %>% 
  ggplot(aes(x=larval_counts, y=proportion, color=zero_inf, shape=tech_rep)) +geom_point() +
  theme(axis.text.x = element_text(angle =30, hjust=1)) + facet_wrap(~ID_mifish, scales="free")


for_plotting %>% 
  filter(., ID_mifish =="Merluccius productus") %>% 
  left_join(hake_count) %>% 
  ggplot(aes(x=Year, y=proportion, color=zero_inf, shape=tech_rep)) +geom_point() +
  theme(axis.text.x = element_text(angle =30, hjust=1)) +facet_wrap(chovy_level~.)



ggsave(filename = "hake_vs_count_drop_out.png",
       width=18,
       height = 12,
       dpi = 200,
       units = c("in"))
  

```

```{r}
larvae_data %>% 
  filter(., ID_mifish =="Cyclothone atraria") %>% 
  ggplot(aes(x=larval_counts)) +geom_histogram()


larvae_data %>% 
  filter(., ID_mifish =="Cyclothone atraria") %>% 
   mutate(chovy_level = case_when(larval_counts > 4  ~"High",
                              larval_counts >0  ~"Low",
                              TRUE ~"Not Counted"))  -> cycl_count


cv_calcofi %>% 
  filter(., ID_mifish=="Cyclothone atraria") %>% 
  left_join(cycl_count) %>% 
  ggplot(aes(x=larval_counts,y=cvReads)) +geom_point() +ggtitle("Cyclothone atraria")

ggsave(filename = "cycla_cv_vs_larval_counts.png",
       width=18,
       height = 12,
       dpi = 200,
       units = c("in"))


for_plotting %>% 
  filter(., ID_mifish =="Cyclothone atraria") %>% 
  left_join(cycl_count) %>% 
  ggplot(aes(x=larval_counts, y=mifish_reads, color=zero_inf, shape=tech_rep)) +geom_point() +
  theme(axis.text.x = element_text(angle =30, hjust=1)) + facet_wrap(~ID_mifish, scales="free")



for_plotting %>% 
  filter(., ID_mifish =="Cyclothone atraria") %>% 
  left_join(cycl_count) %>% 
  ggplot(aes(x=larval_counts, y=proportion, color=zero_inf, shape=tech_rep)) +geom_point() +
  theme(axis.text.x = element_text(angle =30, hjust=1)) + facet_wrap(~ID_mifish, scales="free")


for_plotting %>% 
  filter(., ID_mifish =="Cyclothone atraria") %>% 
  left_join(cycl_count) %>% 
  ggplot(aes(x=Year, y=proportion, color=zero_inf, shape=tech_rep)) +geom_point() +
  theme(axis.text.x = element_text(angle =30, hjust=1)) +facet_wrap(chovy_level~.)



ggsave(filename = "cycla_vs_count_drop_out.png",
       width=18,
       height = 12,
       dpi = 200,
       units = c("in"))
  

```

