---
title: "Hurdle Model Play"
author: "Zack Gold"
date: "7/15/2022"
output: ''
---

```{r}
library(dotwhisker)
library(tidyverse)
library(ggcorrplot)
library(vegan)
library(rstanarm)
library(broom.mixed)
library(glmmTMB)
library(ggeffects)
library(effects)
library(parameters)
library(ggplot2); theme_set(theme_bw())
library(knitr)
library(bbmle) #for AICtab
library(reshape)
library(here)

```


# glmmtmb

```{R}


glmmTMB_log_combo<- glmmTMB(mean ~ 0 + (1 + temp_std | ID_main/station),
                            family = ziGamma(link = "log"),
                         ziformula = ~ temp_std + ID_main + station,
                             data = test_a)
saveRDS(glmmTMB_log_combo, here("data","glmmTMB_log_combo.RDS"))

summary(glmmTMB_log_combo )
glmmTMB_log_combo_R1<- glmmTMB(mean ~ 0 + (1 + temp_std | ID_main/station),
                            family = ziGamma(link = "log"),
                         ziformula = ~ ID_main +station,
                             data = test_a)

saveRDS(glmmTMB_log_combo_R1, here("data","glmmTMB_log_combo_R1.RDS"))

glmmTMB_log_combo_R1.5<- glmmTMB(mean ~ 0 + (1 + temp_std | ID_main/station),
                            family = ziGamma(link = "log"),
                         ziformula = ~ ID_main * station,
                             data = test_a)

glmmTMB_log_combo_zi1<- glmmTMB(mean ~ 0 + (1 + temp_std | ID_main/station),
                            family = ziGamma(link = "log"),
                         ziformula = ~ 1,
                             data = test_a)

glmmTMB_log_combo_zi1<- glmmTMB(mean ~ 0 + (1 + temp_std | ID_main/station),
                            family = ziGamma(link = "log"),
                         ziformula = ~ 1,
                             data = test_a)



AICtab(glmmTMB_log_combo,glmmTMB_log_combo_zi1,
       glmmTMB_log_combo_R1,
       glmmTMB_log_combo_R1.5)


glmmTMB_r2<- glmmTMB(mean ~ 0 + (1 + temp_std | ID_main/station),
                            family = tweedie,
                         ziformula = ~ temp_std + ID_main + station,
                             data = test_a)

glmmTMB_r2.5<- glmmTMB(mean ~ 0 + (1 + temp_std | ID_main/station),
                            family = tweedie(link = "log"),
                         ziformula = ~ temp_std + ID_main + station,
                             data = test_a)

glmmTMB_r3<- glmmTMB(mean ~ 0 + (1 + temp_std | ID_main/station),
                            family = gaussian,
                         ziformula = ~ temp_std + ID_main + station,
                             data = test_a)

glmmTMB_r4<- glmmTMB(mean ~ 0 + (1 + temp_std | ID_main/station),
                            family = gaussian(link = "log"),
                     start=c(10,0,0),
                         ziformula = ~ temp_std + ID_main + station,
                             data = test_a)


```


```{r}
library(DHARMa)

glmmTMB_log_combo_simres <- simulateResiduals(glmmTMB_log_combo)
plot(glmmTMB_log_combo_simres)


ggsave(
  file = here::here("analysis", "figures", "glmmTMB_log_combo_simres.jpeg"),
  width = 12,
  height = 8
  )

glmmTMB_log_combo_R1_simres <- simulateResiduals(glmmTMB_log_combo_R1)
plot(glmmTMB_log_combo_R1_simres)


 
 
glmmTMB_r2_simres <- simulateResiduals(glmmTMB_r2)
plot(glmmTMB_r2_simres)


glmmTMB_r2.5_combo_simres <- simulateResiduals(glmmTMB_r2.5)
plot(glmmTMB_r2.5_combo_simres)


glmmTMB_r3_simres <- simulateResiduals(glmmTMB_r3)
plot(glmmTMB_log_combo_simres)


glmmTMB_r4_simres <- simulateResiduals(glmmTMB_r4)
plot(glmmTMB_log_combo_simres)


AICtab(glmmTMB_log_combo,
       glmmTMB_log_combo_R1,
       glmmTMB_r2,
       glmmTMB_r2.5,
       glmmTMB_r3,
       glmmTMB_r4)
```

```{r}
library(car)
glmmTMB_log_combo <- readRDS(file= here("data","glmmTMB_log_combo.RDS"))

Anova(glmmTMB_log_combo)

if (requireNamespace("car") && getRversion() >= "3.6.0") {
Anova(glmmTMB_log_combo) ## default type II
Anova(glmmTMB_log_combo,type="III")
}

library(effects)
effects_ok <- (requireNamespace("effects") && getRversion() >= "3.6.0")
if (effects_ok) {
(ae <- allEffects(glmmTMB_log_combo))
plot(ae)
}

summary(glmmTMB_log_combo)


tidy(glmmTMB_log_combo,conf.int = TRUE)
if (requireNamespace("broom.mixed") && requireNamespace("dotwhisker")) {
t1 <- broom.mixed::tidy(glmmTMB_log_combo)
t1 <- transform(t1,
term=sprintf("%s.%s", component, term))
if (packageVersion("dotwhisker")>"0.4.1") {
dw <- dwplot(t1)
} else {
glmmTMB_log_combo$coefficients <- TRUE ## hack!
dw <- dwplot(glmmTMB_log_combo,by_2sd=FALSE)
}
print(dw+geom_vline(xintercept=0,lty=2))
}

```


#Quick and dirty plot

```{r}
glmmTMB_log_combo <- readRDS(here("data","glmmTMB_log_combo.RDS"))

test_a <- readRDS(file=here("data","calcofi_model_means.RDS"))

glmmTMB_log_combo

newdata0 = newdata = unique(test_a[,c("ID_main","station","temp_std")])
temp = predict(glmmTMB_log_combo, newdata, se.fit=TRUE, type="response")
temp_1 = predict(glmmTMB_log_combo, newdata, se.fit=TRUE, type = "zprob")
temp_2 = predict(glmmTMB_log_combo, newdata, se.fit=TRUE, type = "conditional")

newdata$predFE = temp$fit
newdata$predFE.min = temp$fit-1.98*temp$se.fit
newdata$predFE.max = temp$fit+1.98*temp$se.fit


newdata$pzeroFE = temp_1$fit
newdata$pzeroFE.min = temp_1$fit-1.98*temp_1$se.fit
newdata$pzeroFE.max = temp_1$fit+1.98*temp_1$se.fit


newdata$posFE = temp_2$fit
newdata$posFE.min = temp_2$fit-1.98*temp_2$se.fit
newdata$posFE.max = temp_2$fit+1.98*temp_2$se.fit
```


```{r}

test_a %>% 
  left_join(newdata) %>% 
  filter(., ID_main %in% c("Stenobrachius nannochir","Triphoturus mexicanus")) %>% 
  ggplot(., aes(x= temp_std))+
  geom_point(aes(y=PA_biomass))+
  geom_point(aes(y=pzeroFE),colour="red", alpha=0.2)+
  geom_pointrange(aes(y=pzeroFE,ymin=pzeroFE.min , ymax=pzeroFE.max), colour="red",alpha=0.2) +theme_bw()+
  facet_wrap(ID_main~station, scales="free_y")


ggsave(
  file = here::here("analysis", "figures", "glmmTMB_pzero_model_fit.jpeg"),
  width = 16,
  height = 16
  )

test_a %>% 
  left_join(newdata) %>% 
  filter(., ID_main %in% c("Stenobrachius nannochir","Triphoturus mexicanus")) %>% 
  ggplot(., aes(x= temp_std))+
  geom_point(aes(y=mean))+
  geom_point(aes(y=posFE),colour="red", alpha=0.2)+
  geom_pointrange(aes(y=posFE,ymin=posFE.min , ymax=posFE.max), colour="red",alpha=0.2) +theme_bw()+
  facet_wrap(ID_main~station, scales="free_y") + scale_y_continuous(trans=scales::pseudo_log_trans(base = 10))


ggsave(
  file = here::here("analysis", "figures", "glmmTMB_pos_model_fit.jpeg"),
  width = 16,
  height = 16
  )

trait_edna_1 <-
read.csv("../data/habitat_association_to_check_art.csv", header = T)
as.data.frame(trait_edna_1) -> trait_edna

trait_edna %>% 
  filter(., Type =="Southern Mesopelagic") -> so_meso

test_a %>% 
  left_join(newdata) %>% 
  filter(., ID_main %in% so_meso$ID_main) %>% 
  ggplot(., aes(x= temp_std))+
  geom_point(aes(y=mean))+
  geom_point(aes(y=posFE),colour="red", alpha=0.2)+
  geom_pointrange(aes(y=posFE,ymin=posFE.min , ymax=posFE.max), colour="red",alpha=0.2) +theme_bw()+
  facet_wrap(ID_main~station, scales="free_y") + scale_y_continuous(trans=scales::pseudo_log_trans(base = 10))


ggsave(
  file = here::here("analysis", "figures", "glmmTMB_pos_model_fit_so_meso.jpeg"),
  width = 16,
  height = 16
  )

```

```{r}


tidy(glmmTMB_log_combo_zi1)

glmmTMB_log_combo_zi1$fit$parfull
fixef(glmmTMB_log_combo)
glmmTMB_log_combo$fit$parfull


glmmTMB_log_combo$sdr



sims=simulate(glmmTMB_log_combo, seed = 1, nsim = 1000)

sims$sim_1 


model_parameters(glmmTMB_log_combo)
emmeans(glmmTMB_log_combo)

glmmTMB_log_combo
broom.mixed::tidy(glmmTMB_log_combo)

summary(glmmTMB_log_combo)

glmmTMB_log_combo$frame

ranef(glmmTMB_log_combo) -> rr

as.data.frame(rr)


as.data.frame(rr) %>% 
  filter(., term=="temp_std") -> rr_temp

rr_temp %>% 
  mutate(., T_statistic= condval/condsd) %>% 
  filter(., T_statistic  > 1 | T_statistic < -1) %>% 
   separate(., grp, into=c("station","ID_main"), remove=F, sep=":") %>% 
  filter(., !is.na(ID_main))-> signficant_taxa

rr_temp %>% 
  filter(., grpvar !="ID_main") %>% 
  separate(., grp, into=c("station","ID_main"), remove=F, sep=":") -> rr_t2

rr_temp %>% 
  filter(., grpvar =="ID_main") %>% 
  separate(., grp, into=c("ID_main","station"), remove=F, sep=":") %>% 
  mutate(., station=tidyr::replace_na(station,"Species")) %>% 
  dplyr::select(component ,grpvar  ,  term  ,    grp    ,   station ,  ID_main ,  condval,  
,condsd )-> rr_t3


rbind(rr_t2,rr_t3)-> back_combo 
back_combo %>% 
      mutate(., T_statistic= condval/condsd) %>% 
  mutate(., station = case_when(
str_detect(station, "Pt.C") ~ "Pt. Conception",
str_detect(station, "SaNI") ~ "San Nicholas Island",
str_detect(station, "SDIn") ~ "San Diego Inshore",
str_detect(station, "SDOf") ~ "San Diego Offshore",
TRUE ~"Species"),
Signficant = case_when(
T_statistic  > 1 ~ "+",
T_statistic  < -1 ~ "-",
TRUE ~ ""
)) %>% 
   ggplot(., aes(x = station, y = ID_main, fill = T_statistic)) + geom_tile()   + xlab("Station") + ylab("Species") + scale_fill_viridis_c( option = "plasma", limits=c(-4, 4), breaks=c(-4,-2,-1,-0,1,2,4)) + geom_text(aes(label =
  Signficant),color="white", size=8)+
  theme_bw() +
  theme(axis.text.y=element_text(size=14),
axis.text.x = element_text(
size = 14,
angle = 30,
hjust = 1
),
panel.background = element_rect(fill = 'white', colour = 'white'),
panel.grid.major = element_blank(),
panel.grid.minor = element_blank(),
axis.title.x = element_blank(),
axis.title.y = element_text(size = 18, angle = 90, face = "bold"),
strip.background = element_rect(fill = 'white'),
strip.text.x = element_text(size = 15),
legend.text = element_text(size = 10),
legend.title = element_text(size = 15),
axis.line = element_line(colour = 'black')
) + guides(fill=guide_legend(title="T Statistic")) 




ggsave(
  file = here::here("analysis", "figures", "glmmTMB_model_fit_RE_values.jpeg"),
  width = 12,
  height = 12
  )


```


```{R}
confint(glmmTMB_log_combo) %>% 
  as_tibble(rownames = "component") %>% 
  ggplot(., aes(y=component)) +
  geom_point(aes(x=Estimate)) +
  geom_errorbarh(aes(xmax = `97.5 %`, xmin = `2.5 %`, height = 0)) +
  geom_vline(xintercept = 0, linetype="dashed", 
                color = "red", size=1.5)



ggsave(
  file = here::here("analysis", "figures", "glmmTMB_model_fit_confidence_intervals_parms_values.jpeg"),
  width = 16,
  height = 20
  )
```
